-- ONE-TIME PRODUCTION SCHEMA SYNCHRONIZATION: VERSION 2
-- MarketPilot production schema sync v2
--
-- NOT a Laravel historical migration.
-- Do not place this file in database/migrations/.
-- Do not run this through php artisan migrate.
--
-- Purpose:
-- Synchronize the two missing onboarding/compliance tables (public.legal_acceptances
-- and public.pending_onboardings) required by the current application codebase into
-- the production Supabase PostgreSQL database.
--
-- Safety:
-- - Run only after reviewing database/production/README.md.
-- - Run with psql ON_ERROR_STOP enabled.
-- - Run from a controlled maintenance process with a recoverable backup.
-- - All operations are strictly idempotent and non-destructive.
-- - Existing user, business, product, design, campaign, and session data is untouched.
-- - Deprecated contact fields (business_contact_number, business_email, website_social_page)
--   are omitted from pending_onboardings per migration 2026_09_17_042848.
-- - RLS is enabled on both new tables with access restricted to application roles
--   (marketpilot_app, postgres). No public/anonymous access is permitted.

\set ON_ERROR_STOP on
\echo 'MarketPilot production schema sync v2: PREPARE/EXECUTE ONLY AFTER HUMAN APPROVAL'

BEGIN;

SET LOCAL lock_timeout = '10s';
SET LOCAL statement_timeout = '10min';

-- =============================================================================
-- 1. PREFLIGHT SAFETY CHECKS
-- =============================================================================
DO $$
BEGIN
    -- Assert core application tables exist
    IF to_regclass('public.users') IS NULL THEN
        RAISE EXCEPTION 'Preflight failed: expected table public.users does not exist';
    END IF;

    IF to_regclass('public.businesses') IS NULL THEN
        RAISE EXCEPTION 'Preflight failed: expected table public.businesses does not exist';
    END IF;

    -- Assert public.migrations does NOT exist (production does not use Laravel migration ledger)
    IF to_regclass('public.migrations') IS NOT NULL THEN
        RAISE EXCEPTION 'Preflight failed: public.migrations exists; stop and use a separately approved migration-ledger plan';
    END IF;

    -- Assert required application role exists for RLS policies
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'marketpilot_app') THEN
        RAISE EXCEPTION 'Preflight failed: expected database role marketpilot_app does not exist';
    END IF;

    -- Assert public.users has expected schema from previous sync
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'users' AND column_name = 'username'
    ) THEN
        RAISE EXCEPTION 'Preflight failed: public.users is missing username column';
    END IF;

    -- Assert public.businesses has expected barangay column
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_schema = 'public' AND table_name = 'businesses' AND column_name = 'barangay'
    ) THEN
        RAISE EXCEPTION 'Preflight failed: public.businesses is missing barangay column';
    END IF;
END $$;

-- =============================================================================
-- 2. CREATE TABLE: public.legal_acceptances
-- Matching database/migrations/2026_09_16_200000_create_legal_acceptances_table.php
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.legal_acceptances (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    document_type varchar(64) NOT NULL,
    document_version varchar(32) NOT NULL DEFAULT 'v1.0',
    accepted_at timestamp without time zone NOT NULL,
    created_at timestamp without time zone NULL,
    updated_at timestamp without time zone NULL
);

-- Foreign key constraint with ON DELETE CASCADE
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'legal_acceptances_user_id_fkey'
          AND conrelid = 'public.legal_acceptances'::regclass
    ) THEN
        ALTER TABLE public.legal_acceptances
            ADD CONSTRAINT legal_acceptances_user_id_fkey
            FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;
    END IF;
END $$;

-- Unique constraint: (user_id, document_type, document_version)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'legal_acceptances_user_doc_ver_unique'
          AND conrelid = 'public.legal_acceptances'::regclass
    ) THEN
        ALTER TABLE public.legal_acceptances
            ADD CONSTRAINT legal_acceptances_user_doc_ver_unique
            UNIQUE (user_id, document_type, document_version);
    END IF;
END $$;

-- Index: (user_id, document_type)
CREATE INDEX IF NOT EXISTS legal_acceptances_user_id_document_type_index
    ON public.legal_acceptances (user_id, document_type);

-- RLS Configuration for legal_acceptances
ALTER TABLE public.legal_acceptances ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policy
        WHERE polrelid = 'public.legal_acceptances'::regclass
          AND polname = 'marketpilot_app_full_access'
    ) THEN
        CREATE POLICY marketpilot_app_full_access
            ON public.legal_acceptances
            AS PERMISSIVE
            FOR ALL
            TO marketpilot_app, postgres
            USING (true)
            WITH CHECK (true);
    END IF;
END $$;

-- =============================================================================
-- 3. CREATE TABLE: public.pending_onboardings
-- Matching database/migrations/2026_09_16_220000_create_pending_onboardings_table.php
-- with contact fields removed per 2026_09_17_042848_remove_contact_fields_from_businesses_and_pending_table.php
-- =============================================================================
CREATE TABLE IF NOT EXISTS public.pending_onboardings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token varchar(64) NOT NULL,
    registration_type varchar(32) NOT NULL DEFAULT 'normal',
    email varchar(255) NOT NULL,
    username varchar(255) NULL,
    password_hash varchar(255) NULL,
    provider_name varchar(255) NULL,
    provider_id varchar(255) NULL,
    avatar text NULL,

    -- Email verification
    email_verification_code varchar(6) NULL,
    email_verification_expires_at timestamp without time zone NULL,
    email_verified_at timestamp without time zone NULL,

    -- Step 1: Personal Information
    first_name varchar(255) NULL,
    middle_name varchar(255) NULL,
    last_name varchar(255) NULL,
    suffix varchar(20) NULL,
    mobile_number varchar(30) NULL,

    -- Step 2: Business Information
    business_name varchar(255) NULL,
    industry varchar(255) NULL,
    category varchar(255) NULL,

    -- Step 3: About & Registration Information
    business_description text NULL,
    business_address varchar(255) NULL,
    barangay varchar(255) NULL,
    city_municipality varchar(255) NULL,
    province varchar(255) NULL,
    region varchar(255) NULL,
    registration_type_field varchar(255) NULL,
    registration_number varchar(255) NULL,
    business_permit_number varchar(255) NULL,
    registration_permit_date date NULL,
    business_registration_document_path varchar(255) NULL,

    -- Legal Documents (JSON state)
    accepted_legal_documents jsonb NULL,

    -- Status & lifecycle
    current_step smallint NOT NULL DEFAULT 1,
    expires_at timestamp without time zone NULL,
    created_at timestamp without time zone NULL,
    updated_at timestamp without time zone NULL
);

-- Unique constraint on token
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'pending_onboardings_token_unique'
          AND conrelid = 'public.pending_onboardings'::regclass
    ) THEN
        ALTER TABLE public.pending_onboardings
            ADD CONSTRAINT pending_onboardings_token_unique UNIQUE (token);
    END IF;
END $$;

-- Indexes matching migration
CREATE INDEX IF NOT EXISTS pending_onboardings_email_index
    ON public.pending_onboardings (email);

CREATE INDEX IF NOT EXISTS pending_onboardings_username_index
    ON public.pending_onboardings (username);

CREATE INDEX IF NOT EXISTS pending_onboardings_provider_id_index
    ON public.pending_onboardings (provider_id);

-- RLS Configuration for pending_onboardings
ALTER TABLE public.pending_onboardings ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policy
        WHERE polrelid = 'public.pending_onboardings'::regclass
          AND polname = 'marketpilot_app_full_access'
    ) THEN
        CREATE POLICY marketpilot_app_full_access
            ON public.pending_onboardings
            AS PERMISSIVE
            FOR ALL
            TO marketpilot_app, postgres
            USING (true)
            WITH CHECK (true);
    END IF;
END $$;

-- =============================================================================
-- 4. POSTFLIGHT INTEGRITY ASSERTIONS
-- =============================================================================
DO $$
DECLARE
    legal_cols_count integer;
    pending_cols_count integer;
    deprecated_cols_count integer;
    legal_rls boolean;
    pending_rls boolean;
BEGIN
    -- Verify legal_acceptances exists with exactly 7 columns
    SELECT count(*) INTO legal_cols_count
    FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'legal_acceptances';

    IF legal_cols_count <> 7 THEN
        RAISE EXCEPTION 'Postflight failed: public.legal_acceptances expected 7 columns, found %', legal_cols_count;
    END IF;

    -- Verify pending_onboardings exists with exactly 36 columns
    SELECT count(*) INTO pending_cols_count
    FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'pending_onboardings';

    IF pending_cols_count <> 36 THEN
        RAISE EXCEPTION 'Postflight failed: public.pending_onboardings expected 36 columns, found %', pending_cols_count;
    END IF;

    -- Assert deprecated contact columns are strictly absent from pending_onboardings
    SELECT count(*) INTO deprecated_cols_count
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'pending_onboardings'
      AND column_name IN ('business_contact_number', 'business_email', 'website_social_page');

    IF deprecated_cols_count > 0 THEN
        RAISE EXCEPTION 'Postflight failed: deprecated contact columns found in pending_onboardings';
    END IF;

    -- Verify RLS is enabled on both tables
    SELECT relrowsecurity INTO legal_rls
    FROM pg_class WHERE oid = 'public.legal_acceptances'::regclass;

    IF legal_rls IS DISTINCT FROM true THEN
        RAISE EXCEPTION 'Postflight failed: RLS is not enabled on public.legal_acceptances';
    END IF;

    SELECT relrowsecurity INTO pending_rls
    FROM pg_class WHERE oid = 'public.pending_onboardings'::regclass;

    IF pending_rls IS DISTINCT FROM true THEN
        RAISE EXCEPTION 'Postflight failed: RLS is not enabled on public.pending_onboardings';
    END IF;

    -- Verify FK on legal_acceptances references users(id) with CASCADE
    IF NOT EXISTS (
        SELECT 1
        FROM information_schema.referential_constraints rc
        JOIN information_schema.table_constraints tc ON tc.constraint_name = rc.constraint_name
        WHERE tc.table_schema = 'public'
          AND tc.table_name = 'legal_acceptances'
          AND rc.delete_rule = 'CASCADE'
    ) THEN
        RAISE EXCEPTION 'Postflight failed: legal_acceptances foreign key with ON DELETE CASCADE is missing';
    END IF;
END $$;

COMMIT;

\echo 'MarketPilot production schema sync v2 completed successfully.'
