-- Synthetic partial production schema for the disposable synchronization test.
-- No production data, credentials, or external connections are used.

CREATE TABLE public.users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    email varchar(255) NOT NULL UNIQUE,
    email_verified_at timestamp NULL,
    email_verification_code varchar(255) NULL,
    email_verification_expires_at timestamp NULL,
    password varchar(255) NOT NULL,
    two_factor_secret text NULL,
    two_factor_recovery_codes text NULL,
    two_factor_confirmed_at timestamp NULL,
    onboarding_completed boolean NOT NULL DEFAULT false,
    onboarding_completed_at timestamp NULL,
    provider_name varchar(255) NULL,
    provider_id varchar(255) NULL,
    avatar varchar(255) NULL,
    remember_token varchar(100) NULL,
    created_at timestamp NULL,
    updated_at timestamp NULL
);

CREATE TABLE public.businesses (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL UNIQUE REFERENCES public.users(id) ON DELETE CASCADE,
    name varchar(255) NOT NULL,
    industry varchar(255) NOT NULL,
    category varchar(255) NOT NULL,
    description text NULL,
    target_audience text NULL,
    unique_selling_point text NULL,
    content_style varchar(255) NULL,
    default_tagline_behavior varchar(255) NULL,
    marketing_preferences jsonb NULL,
    created_at timestamp NULL,
    updated_at timestamp NULL
);

CREATE TABLE public.events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NULL REFERENCES public.users(id) ON DELETE SET NULL,
    name varchar(255) NOT NULL,
    description text NULL,
    date date NOT NULL,
    type varchar(255) NOT NULL,
    category varchar(255) NULL,
    is_long_weekend boolean NOT NULL DEFAULT false,
    long_weekend_details varchar(255) NULL,
    shifted_from_date date NULL,
    proclamation_no varchar(255) NULL,
    is_global boolean NOT NULL DEFAULT false,
    country varchar(255) NULL,
    source varchar(255) NULL,
    created_at timestamp NULL,
    updated_at timestamp NULL,
    CONSTRAINT events_user_date_name_unique UNIQUE (user_id, date, name)
);

CREATE TABLE public.campaigns (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    business_id bigint NOT NULL REFERENCES public.businesses(id) ON DELETE CASCADE,
    product_id bigint NULL,
    event_id bigint NULL REFERENCES public.events(id) ON DELETE SET NULL,
    name varchar(255) NOT NULL,
    description text NULL,
    objective text NULL,
    target_audience text NULL,
    start_date date NULL,
    end_date date NULL,
    status varchar(255) NOT NULL DEFAULT 'draft',
    created_at timestamp NULL,
    updated_at timestamp NULL
);

INSERT INTO public.users
    (id, name, email, password, email_verified_at, onboarding_completed, created_at, updated_at)
VALUES
    (1, 'Synthetic Maria One', 'maria@one.example.invalid', 'synthetic-password', now(), false, now(), now()),
    (2, 'Synthetic Maria Two', 'maria@two.example.invalid', 'synthetic-password', now(), false, now(), now()),
    (3, 'Synthetic Maria Three', 'maria@three.example.invalid', 'synthetic-password', now(), false, now(), now()),
    (4, 'Synthetic Unsupported', 'ma+ria@example.invalid', 'synthetic-password', now(), false, now(), now()),
    (5, 'Legacy User', '@legacy.example.invalid', 'synthetic-password', now(), false, now(), now()),
    (6, '!!!', '@fallback.example.invalid', 'synthetic-password', now(), false, now(), now()),
    (7, 'Synthetic Preserved', 'preserve@example.invalid', 'synthetic-password', now(), false, now(), now()),
    (8, 'Synthetic MarketPilot', 'marketpilot@example.invalid', 'synthetic-password', now(), false, now(), now());

INSERT INTO public.businesses
    (user_id, name, industry, category, description, content_style)
VALUES
    (1, 'Synthetic Business', 'Retail & E-Commerce', 'Online Shop', 'Synthetic business only.', 'synthetic-style');

CREATE ROLE marketpilot_app NOLOGIN;

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

CREATE POLICY marketpilot_app_full_access
    ON public.users
    AS PERMISSIVE
    FOR ALL
    TO marketpilot_app, postgres
    USING (true)
    WITH CHECK (true);
