import { Head, Link, usePage } from '@inertiajs/react';
import {
    ArrowRight,
    BarChart3,
    Building2,
    Calendar,
    CalendarDays,
    Check,
    CheckCircle2,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    Clock,
    Compass,
    Cpu,
    Download,
    ExternalLink,
    Eye,
    HeartPulse,
    ImageIcon,
    Layers,
    Megaphone,
    Menu,
    Moon,
    Package,
    ShieldCheck,
    ShoppingBag,
    ShoppingCart,
    SlidersHorizontal,
    Sparkles,
    Sun,
    X,
    Zap,
} from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import AppLogoIcon from '@/components/app-logo-icon';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { dashboard, home, login, register } from '@/routes';

/*
|--------------------------------------------------------------------------
| Theme Management
|--------------------------------------------------------------------------
*/

type Theme = 'light' | 'dark';

const getInitialTheme = (): Theme => {
    if (typeof window === 'undefined') {
        return 'light';
    }

    const savedTheme = window.localStorage.getItem('theme');

    if (savedTheme === 'dark' || savedTheme === 'light') {
        return savedTheme;
    }

    return window.matchMedia('(prefers-color-scheme: dark)').matches
        ? 'dark'
        : 'light';
};

/*
|--------------------------------------------------------------------------
| Dedicated Public Showcase Creatives (Generated by System Pipeline)
|--------------------------------------------------------------------------
*/

interface ShowcaseCreative {
    id: string;
    businessName: string;
    industry: string;
    category: string;
    productName: string;
    price: string;
    tagline: string;
    event: string;
    mode: 'Product Reference' | 'Creative Generation';
    modeType: 'A' | 'B';
    ratio: string;
    image: string;
    bgImages: string[];
}

const showcaseCreatives: ShowcaseCreative[] = [
    {
        id: 'coffee',
        businessName: 'Kape Barako Heritage',
        industry: 'Cafe & Beverages',
        category: 'Coffee & Cold Brew',
        productName: 'Barako Reserve Cold Brew',
        price: '₱165',
        tagline: '18-Hour Slow Brew',
        event: 'Philippine Independence Day',
        mode: 'Product Reference',
        modeType: 'A',
        ratio: '1:1 Square',
        image: '/images/showcase/barako-ad-1x1.jpg',
        bgImages: [
            '/images/showcase/ube-ad-1x1.jpg',
            '/images/showcase/linen-ad-1x1.jpg',
        ],
    },
    {
        id: 'bakery',
        businessName: 'Pampanga Sweet Treats',
        industry: 'Bakery & Pastries',
        category: 'Artisanal Cakes',
        productName: 'Ube Halaya Dream Cake',
        price: '₱480',
        tagline: 'Silky Ube Velvet Cream',
        event: 'Paskong Pinoy Grand Season',
        mode: 'Creative Generation',
        modeType: 'B',
        ratio: '1:1 Square',
        image: '/images/showcase/ube-ad-1x1.jpg',
        bgImages: [
            '/images/showcase/calamansi-ad-1x1.jpg',
            '/images/showcase/barako-ad-1x1.jpg',
        ],
    },
    {
        id: 'fashion',
        businessName: 'Laguna Weavers Co.',
        industry: 'Retail & Apparel',
        category: 'Handcrafted Fashion',
        productName: 'Heritage Linen Camp Shirt',
        price: '₱1,250',
        tagline: 'Handcrafted Tropical Weave',
        event: 'Mid-Month 15/30 Payday Sale',
        mode: 'Product Reference',
        modeType: 'A',
        ratio: '1:1 Square',
        image: '/images/showcase/linen-ad-1x1.jpg',
        bgImages: [
            '/images/showcase/barako-ad-1x1.jpg',
            '/images/showcase/calamansi-ad-1x1.jpg',
        ],
    },
    {
        id: 'beauty',
        businessName: 'Aura Botanicals PH',
        industry: 'Beauty & Wellness',
        category: 'Botanical Skincare',
        productName: 'Kalamansi Glow Botanical Serum',
        price: '₱690',
        tagline: 'Fresh Vitamin C Brightening',
        event: 'Mid-Month 15/30 Payday Sale',
        mode: 'Creative Generation',
        modeType: 'B',
        ratio: '1:1 Square',
        image: '/images/showcase/calamansi-ad-1x1.jpg',
        bgImages: [
            '/images/showcase/linen-ad-1x1.jpg',
            '/images/showcase/ube-ad-1x1.jpg',
        ],
    },
];

/*
|--------------------------------------------------------------------------
| Welcome Component
|--------------------------------------------------------------------------
*/

export default function Welcome() {
    const { auth } = usePage<{ auth?: { user?: any } }>().props;

    const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
    const [theme, setTheme] = useState<Theme>(getInitialTheme);
    const [isScrolled, setIsScrolled] = useState(false);

    // Dedicated Public Showcase State with Automatic Rotation
    const [activeShowcaseIndex, setActiveShowcaseIndex] = useState(0);
    const [isAutoPlayPaused, setIsAutoPlayPaused] = useState(false);

    const activeCreative = showcaseCreatives[activeShowcaseIndex];

    useEffect(() => {
        if (isAutoPlayPaused) return;

        const interval = setInterval(() => {
            setActiveShowcaseIndex((prev) => (prev + 1) % showcaseCreatives.length);
        }, 5000);

        return () => clearInterval(interval);
    }, [isAutoPlayPaused]);

    const handlePrevShowcase = () => {
        setActiveShowcaseIndex((prev) =>
            prev === 0 ? showcaseCreatives.length - 1 : prev - 1,
        );
    };

    const handleNextShowcase = () => {
        setActiveShowcaseIndex((prev) =>
            (prev + 1) % showcaseCreatives.length,
        );
    };

    // Interactive Calendar Showcase State
    const [calendarCategory, setCalendarCategory] = useState<
        'all' | 'regular' | 'special_non_working' | 'islamic'
    >('all');

    // Interactive Pricing Toggle
    const [billingCycle, setBillingCycle] = useState<'monthly' | 'annual'>(
        'monthly',
    );

    // Interactive FAQ
    const [openFaqIndex, setOpenFaqIndex] = useState<number | null>(0);

    useEffect(() => {
        document.documentElement.classList.toggle('dark', theme === 'dark');
        window.localStorage.setItem('theme', theme);
    }, [theme]);

    useEffect(() => {
        const handleScroll = () => {
            setIsScrolled(window.scrollY > 20);
        };
        window.addEventListener('scroll', handleScroll, { passive: true });
        return () => window.removeEventListener('scroll', handleScroll);
    }, []);

    const toggleTheme = () => {
        setTheme((prev) => (prev === 'dark' ? 'light' : 'dark'));
    };

    const upcomingCalendarDates = [
        {
            name: 'Araw ng Kagitingan',
            date: 'April 9',
            type: 'Regular Holiday',
            days: 'In 50 days',
            longWeekend: true,
        },
        {
            name: 'Labor Day (Araw ng Manggagawa)',
            date: 'May 1',
            type: 'Regular Holiday',
            days: 'In 72 days',
            longWeekend: false,
        },
        {
            name: 'Independence Day (Araw ng Kalayaan)',
            date: 'June 12',
            type: 'Regular Holiday',
            days: 'In 114 days',
            longWeekend: true,
        },
        {
            name: 'Ninoy Aquino Day',
            date: 'August 21',
            type: 'Special Non-Working',
            days: 'Upcoming',
            longWeekend: false,
        },
        {
            name: 'National Heroes Day',
            date: 'August 25',
            type: 'Regular Holiday',
            days: 'Upcoming',
            longWeekend: true,
        },
        {
            name: 'All Saints’ Day (Undas)',
            date: 'November 1',
            type: 'Special Non-Working',
            days: 'Upcoming',
            longWeekend: true,
        },
        {
            name: 'Christmas Day (Pasko)',
            date: 'December 25',
            type: 'Regular Holiday',
            days: 'Upcoming',
            longWeekend: true,
        },
        {
            name: 'Rizal Day',
            date: 'December 30',
            type: 'Regular Holiday',
            days: 'Upcoming',
            longWeekend: false,
        },
    ];

    const filteredDates = upcomingCalendarDates.filter((item) => {
        if (calendarCategory === 'all') {
            return true;
        }

        if (calendarCategory === 'regular') {
            return item.type === 'Regular Holiday';
        }

        if (calendarCategory === 'special_non_working') {
            return item.type === 'Special Non-Working';
        }

        return true;
    });

    const faqs = [
        {
            q: 'How does the Philippine Marketing Calendar automate holiday visuals?',
            a: 'MarketPilot continuously synchronizes with official Philippine proclamations, including movable Islamic dates and nationwide special non-working declarations. It calculates long-weekend metadata so you can launch promotional campaigns 2 to 3 weeks ahead of every major retail opportunity.',
        },
        {
            q: 'Can I use my existing product catalog and brand assets?',
            a: 'Yes. You can upload products, prices, product descriptions, reference photos, and configure your business / shop name. The AI generator automatically factors your brand identity and voice (friendly, luxurious, professional) into finished visuals.',
        },
        {
            q: 'What download formats are supported for marketing campaigns?',
            a: 'Every generated visual can be exported in PNG (lossless with transparent overlay options), JPEG (web and social-optimized), and vector-wrapped SVG formats. All visual resolutions are scaled for Instagram (1:1), Facebook Feed/Stories (4:5), and Website Banners (16:9).',
        },
        {
            q: 'Do I own full commercial rights to generated creatives?',
            a: 'Absolutely. All marketing visuals generated through MarketPilot belong 100% to your business for commercial distribution across social ads, e-commerce stores, billboards, and print materials.',
        },
        {
            q: 'How fast is the visual generation process?',
            a: 'Visual prompts and design concepts are generated instantly. High-fidelity rendering with custom lighting and brand integration typically completes in under 15 seconds.',
        },
    ];

    return (
        <>
            <Head title="MarketPilot — AI Marketing Automation & Creative Engine" />

            <div className="relative min-h-screen bg-background text-foreground transition-colors duration-200 selection:bg-primary/20 selection:text-primary">
                {/* Ambient Fixed Background Glow Orbs for Landing Page */}
                <div className="pointer-events-none fixed inset-0 -z-10 overflow-hidden">
                    <div className="absolute -top-40 left-1/4 h-[550px] w-[550px] rounded-full bg-primary/12 blur-[140px] dark:bg-primary/15" />
                    <div className="absolute top-1/3 -right-32 h-[500px] w-[500px] rounded-full bg-blue-500/10 blur-[130px] dark:bg-blue-500/15" />
                    <div className="absolute top-2/3 -left-32 h-[450px] w-[450px] rounded-full bg-purple-500/10 blur-[130px] dark:bg-purple-500/15" />
                </div>

                {/* ==========================================================
                    TOP FIXED NAVIGATION HEADER (GLASSMORPHISM)
                =========================================================== */}

                <header
                    className={`fixed top-0 inset-x-0 z-50 w-full transition-all duration-300 ${
                        isScrolled
                            ? 'border-b border-border/80 bg-background/90 shadow-lg shadow-black/5 backdrop-blur-2xl'
                            : 'border-b border-border/40 bg-background/75 backdrop-blur-xl dark:border-white/10'
                    }`}
                >
                    <div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-4 sm:px-6 lg:px-8">
                        {/* Brand Logo with Glow */}
                        <Link
                            href={home()}
                            className="group flex items-center gap-3 focus:outline-none"
                        >
                            <div className="relative flex h-9 w-9 items-center justify-center rounded-xl bg-primary text-primary-foreground shadow-md shadow-primary/25 transition-transform duration-200 group-hover:scale-105">
                                <AppLogoIcon className="h-5 w-5 fill-current" />
                                <div className="absolute inset-0 -z-10 rounded-xl bg-primary/30 blur-sm transition-all group-hover:blur-md" />
                            </div>
                            <div className="flex items-center gap-2">
                                <span className="text-base font-extrabold tracking-tight text-foreground">
                                    MarketPilot
                                </span>
                                <Badge
                                    variant="outline"
                                    className="hidden items-center border-primary/25 bg-primary/10 px-2 py-0.5 font-mono text-[10px] font-bold text-primary shadow-2xs sm:inline-flex"
                                >
                                    Retail Automation
                                </Badge>
                            </div>
                        </Link>

                        {/* Desktop Navigation Links */}
                        <nav className="hidden items-center gap-1.5 rounded-full border border-white/20 bg-card/60 p-1 text-xs font-semibold text-muted-foreground shadow-xs backdrop-blur-md md:flex dark:border-white/10 dark:bg-card/60">
                            <a
                                href="#hero-showcase"
                                className="rounded-full px-3.5 py-1.5 transition-all hover:bg-muted/80 hover:text-foreground"
                            >
                                AI Showcase
                            </a>
                            <a
                                href="#system-flow"
                                className="rounded-full px-3.5 py-1.5 transition-all hover:bg-muted/80 hover:text-foreground"
                            >
                                System Workflow
                            </a>
                            <a
                                href="#features"
                                className="rounded-full px-3.5 py-1.5 transition-all hover:bg-muted/80 hover:text-foreground"
                            >
                                Core Capabilities
                            </a>
                            <a
                                href="#calendar-engine"
                                className="rounded-full px-3.5 py-1.5 transition-all hover:bg-muted/80 hover:text-foreground"
                            >
                                PH Calendar
                            </a>
                            <a
                                href="#subscriptions"
                                className="rounded-full px-3.5 py-1.5 transition-all hover:bg-muted/80 hover:text-foreground"
                            >
                                Subscriptions
                            </a>
                            <a
                                href="#faq"
                                className="rounded-full px-3.5 py-1.5 transition-all hover:bg-muted/80 hover:text-foreground"
                            >
                                FAQ
                            </a>
                        </nav>

                        {/* Right Actions & Theme Switcher */}
                        <div className="flex items-center gap-2.5">
                            {/* Theme Switcher */}
                            <Button
                                type="button"
                                variant="ghost"
                                size="icon"
                                onClick={toggleTheme}
                                aria-label="Toggle theme"
                                className="h-9 w-9 cursor-pointer rounded-xl text-muted-foreground transition-all hover:bg-muted/80 hover:text-foreground"
                            >
                                {theme === 'dark' ? (
                                    <Sun className="h-4 w-4 text-amber-400" />
                                ) : (
                                    <Moon className="h-4 w-4" />
                                )}
                            </Button>

                            {auth?.user ? (
                                <Button
                                    asChild
                                    size="sm"
                                    className="h-9 rounded-xl px-4 text-xs font-bold shadow-lg shadow-primary/25 transition-all hover:scale-105 active:scale-95"
                                >
                                    <Link href={dashboard()}>
                                        Dashboard &rarr;
                                    </Link>
                                </Button>
                            ) : (
                                <div className="hidden items-center gap-2 sm:flex">
                                    <Button
                                        asChild
                                        variant="ghost"
                                        size="sm"
                                        className="h-9 rounded-xl px-3.5 text-xs font-semibold hover:bg-muted/80"
                                    >
                                        <Link href={login()}>Log in</Link>
                                    </Button>
                                    <Button
                                        asChild
                                        size="sm"
                                        className="h-9 rounded-xl px-4 text-xs font-bold shadow-lg shadow-primary/25 transition-all hover:scale-105 active:scale-95"
                                    >
                                        <Link href={register()}>
                                            Get Started Free
                                        </Link>
                                    </Button>
                                </div>
                            )}

                            {/* Mobile Hamburger Button */}
                            <Button
                                type="button"
                                variant="ghost"
                                size="icon"
                                onClick={() =>
                                    setMobileMenuOpen((prev) => !prev)
                                }
                                aria-label="Toggle navigation"
                                className="h-9 w-9 rounded-xl text-muted-foreground hover:text-foreground md:hidden"
                            >
                                {mobileMenuOpen ? (
                                    <X className="h-5 w-5" />
                                ) : (
                                    <Menu className="h-5 w-5" />
                                )}
                            </Button>
                        </div>
                    </div>

                    {/* Mobile Navigation Drawer */}
                    {mobileMenuOpen && (
                        <div className="animate-in space-y-4 border-t border-border/80 bg-card/95 px-4 py-5 backdrop-blur-2xl duration-150 slide-in-from-top-2 md:hidden">
                            <nav className="flex flex-col space-y-2 text-sm font-semibold">
                                <a
                                    href="#hero-showcase"
                                    onClick={() => setMobileMenuOpen(false)}
                                    className="rounded-lg px-3 py-2 text-muted-foreground hover:bg-muted hover:text-foreground"
                                >
                                    AI Showcase Demo
                                </a>
                                <a
                                    href="#system-flow"
                                    onClick={() => setMobileMenuOpen(false)}
                                    className="rounded-lg px-3 py-2 text-muted-foreground hover:bg-muted hover:text-foreground"
                                >
                                    System Workflow
                                </a>
                                <a
                                    href="#features"
                                    onClick={() => setMobileMenuOpen(false)}
                                    className="rounded-lg px-3 py-2 text-muted-foreground hover:bg-muted hover:text-foreground"
                                >
                                    Core Capabilities
                                </a>
                                <a
                                    href="#calendar-engine"
                                    onClick={() => setMobileMenuOpen(false)}
                                    className="rounded-lg px-3 py-2 text-muted-foreground hover:bg-muted hover:text-foreground"
                                >
                                    Philippine Calendar
                                </a>
                                <a
                                    href="#subscriptions"
                                    onClick={() => setMobileMenuOpen(false)}
                                    className="rounded-lg px-3 py-2 text-muted-foreground hover:bg-muted hover:text-foreground"
                                >
                                    Subscriptions
                                </a>
                                <a
                                    href="#faq"
                                    onClick={() => setMobileMenuOpen(false)}
                                    className="rounded-lg px-3 py-2 text-muted-foreground hover:bg-muted hover:text-foreground"
                                >
                                    FAQ
                                </a>
                            </nav>

                            <div className="flex flex-col gap-2 border-t border-border/80 pt-2">
                                {auth?.user ? (
                                    <Button
                                        asChild
                                        className="w-full rounded-xl text-xs font-semibold"
                                    >
                                        <Link href={dashboard()}>
                                            Open Dashboard
                                        </Link>
                                    </Button>
                                ) : (
                                    <>
                                        <Button
                                            asChild
                                            variant="outline"
                                            className="w-full rounded-xl text-xs font-semibold"
                                        >
                                            <Link href={login()}>Log in</Link>
                                        </Button>
                                        <Button
                                            asChild
                                            className="w-full rounded-xl text-xs font-semibold shadow-lg shadow-primary/25"
                                        >
                                            <Link href={register()}>
                                                Get Started Free
                                            </Link>
                                        </Button>
                                    </>
                                )}
                            </div>
                        </div>
                    )}
                </header>

                {/* Fixed Header Height Spacer */}
                <div className="h-16 w-full shrink-0" aria-hidden="true" />

                <main>
                    {/* ==========================================================
                        REDESIGNED HERO SECTION WITH SYSTEM-CONNECTED WORKFLOW
                    =========================================================== */}
                    <section
                        id="hero-showcase"
                        className="relative overflow-hidden pt-10 pb-16 md:pt-16 md:pb-24 lg:pt-20 lg:pb-28"
                    >
                        {/* Ambient Atmospheric Glow */}
                        <div className="pointer-events-none absolute -top-24 left-1/2 -z-10 h-[500px] w-[800px] -translate-x-1/2 rounded-full bg-gradient-to-tr from-primary/15 via-purple-500/10 to-blue-500/10 blur-3xl" />

                        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
                            {/* Hero Two-Column Grid: Left Value Proposition + Right Dominant Showcase Gallery */}
                            <div className="grid gap-12 lg:grid-cols-12 lg:items-center">
                                {/* Left Column: Clear Value Proposition, CTAs & Capability Summary */}
                                <div className="space-y-6 lg:col-span-5 xl:col-span-5">
                                    <div className="inline-flex items-center gap-2 rounded-full border border-primary/20 bg-primary/5 px-3.5 py-1.5 text-xs font-semibold tracking-wide text-primary shadow-xs backdrop-blur-md">
                                        <Sparkles className="h-3.5 w-3.5 text-primary" />
                                        <span>AI-DRIVEN MARKETING CREATIVE STUDIO</span>
                                    </div>

                                    <h1 className="text-3xl leading-[1.12] font-extrabold tracking-tight text-foreground sm:text-4xl lg:text-5xl xl:text-[52px]">
                                        Create Professional<br className="hidden sm:inline" /> Marketing Visuals<br className="hidden sm:inline" /> With AI
                                    </h1>

                                    <p className="text-base leading-relaxed text-muted-foreground sm:text-lg">
                                        Generate campaign-ready marketing visuals from your business information, products, campaign goals, Philippine events, and visual preferences — with or without a product image.
                                    </p>

                                    {/* Action Buttons */}
                                    <div className="flex flex-wrap items-center gap-3.5 pt-1">
                                        <Button
                                            asChild
                                            size="lg"
                                            className="h-12 gap-2 rounded-xl px-7 text-xs font-bold shadow-lg shadow-primary/25 transition-all duration-200 hover:scale-105 hover:shadow-xl hover:shadow-primary/30 active:scale-95 cursor-pointer"
                                        >
                                            <Link href={register()}>
                                                <span>Create Your First Design</span>
                                                <ArrowRight className="h-4 w-4" />
                                            </Link>
                                        </Button>

                                        <Button
                                            asChild
                                            variant="outline"
                                            size="lg"
                                            className="h-12 gap-2 rounded-xl px-6 text-xs font-semibold shadow-2xs transition-all duration-200 hover:scale-105 hover:border-primary/40 hover:bg-muted/50 active:scale-95 cursor-pointer"
                                        >
                                            <a href="#how-it-works">
                                                <Layers className="h-4 w-4 text-primary" />
                                                <span>See How It Works</span>
                                            </a>
                                        </Button>
                                    </div>

                                    {/* Subtle Capability Summary */}
                                    <div className="grid grid-cols-1 gap-2.5 border-t border-border/60 pt-5 text-xs font-medium text-muted-foreground sm:grid-cols-2">
                                        <div className="flex items-center gap-2">
                                            <CheckCircle2 className="h-4 w-4 text-emerald-500 shrink-0" />
                                            <span className="text-foreground">Product reference generation</span>
                                        </div>
                                        <div className="flex items-center gap-2">
                                            <CheckCircle2 className="h-4 w-4 text-emerald-500 shrink-0" />
                                            <span className="text-foreground">Creative generation without product image</span>
                                        </div>
                                        <div className="flex items-center gap-2">
                                            <CheckCircle2 className="h-4 w-4 text-emerald-500 shrink-0" />
                                            <span className="text-foreground">Philippine holiday & event campaigns</span>
                                        </div>
                                        <div className="flex items-center gap-2">
                                            <CheckCircle2 className="h-4 w-4 text-emerald-500 shrink-0" />
                                            <span className="text-foreground">PNG/JPEG export-ready assets</span>
                                        </div>
                                    </div>
                                </div>

                                {/* Right Column: Dominant Editorial Visual Showcase Gallery */}
                                <div
                                    className="relative flex items-center justify-center lg:col-span-7 xl:col-span-7"
                                    onMouseEnter={() => setIsAutoPlayPaused(true)}
                                    onMouseLeave={() => setIsAutoPlayPaused(false)}
                                    aria-roledescription="carousel"
                                    aria-label="AI Marketing Creative Showcase"
                                >
                                    {/* Faded Background Sample (Top-Left Offset) */}
                                    <div
                                        className="pointer-events-none absolute -top-4 -left-4 sm:-left-8 -rotate-6 scale-[0.88] z-0 hidden sm:block w-[280px] sm:w-[340px] aspect-square rounded-3xl overflow-hidden border border-border/40 bg-card/40 opacity-25 dark:opacity-15 blur-[0.5px] shadow-2xl transition-all duration-700"
                                        aria-hidden="true"
                                    >
                                        <img
                                            src={activeCreative.bgImages[0]}
                                            alt=""
                                            className="h-full w-full object-cover grayscale-[20%]"
                                            loading="lazy"
                                        />
                                    </div>

                                    {/* Faded Background Sample (Bottom-Right Offset) */}
                                    <div
                                        className="pointer-events-none absolute -bottom-4 -right-4 sm:-right-8 rotate-6 scale-[0.88] z-0 hidden sm:block w-[280px] sm:w-[340px] aspect-square rounded-3xl overflow-hidden border border-border/40 bg-card/40 opacity-25 dark:opacity-15 blur-[0.5px] shadow-2xl transition-all duration-700"
                                        aria-hidden="true"
                                    >
                                        <img
                                            src={activeCreative.bgImages[1]}
                                            alt=""
                                            className="h-full w-full object-cover grayscale-[20%]"
                                            loading="lazy"
                                        />
                                    </div>

                                    {/* Active Hero Showcase Frame (Editorial Floating Card) */}
                                    <div className="relative z-10 w-full max-w-[400px] sm:max-w-[440px] lg:max-w-[460px] overflow-hidden rounded-3xl border border-white/40 bg-card/95 p-3 shadow-2xl backdrop-blur-xl transition-all duration-500 dark:border-white/15 dark:bg-card/90">
                                        {/* Visual Creative Canvas with Crossfade Transition */}
                                        <div className="relative aspect-square w-full overflow-hidden rounded-2xl bg-black/90 shadow-inner">
                                            {showcaseCreatives.map((creative, index) => (
                                                <img
                                                    key={creative.id}
                                                    src={creative.image}
                                                    alt={`${creative.productName} — ${creative.businessName}`}
                                                    className={`absolute inset-0 h-full w-full object-cover transition-opacity duration-700 ease-in-out ${
                                                        activeShowcaseIndex === index
                                                            ? 'opacity-100 z-10 scale-100'
                                                            : 'opacity-0 z-0 pointer-events-none'
                                                    }`}
                                                    loading={index === 0 ? 'eager' : 'lazy'}
                                                />
                                            ))}
                                        </div>

                                        {/* Minimal Subtle Showcase Footer */}
                                        <div className="flex items-center justify-between px-2 pt-3 text-xs">
                                            <div className="flex items-center gap-2">
                                                <span className="relative flex h-2 w-2">
                                                    <span className="absolute inline-flex h-full w-full animate-ping rounded-full bg-emerald-400 opacity-75" />
                                                    <span className="relative inline-flex h-2 w-2 rounded-full bg-emerald-500" />
                                                </span>
                                                <span className="font-semibold text-foreground text-[11px]">
                                                    AI Creative Showcase
                                                </span>
                                            </div>

                                            {/* Minimalist Pagination & Navigation */}
                                            <div className="flex items-center gap-2">
                                                <div className="flex items-center gap-1">
                                                    <button
                                                        type="button"
                                                        onClick={handlePrevShowcase}
                                                        aria-label="Previous showcase visual"
                                                        className="flex h-6 w-6 items-center justify-center rounded-md text-muted-foreground transition-colors hover:bg-muted hover:text-foreground cursor-pointer"
                                                    >
                                                        <ChevronLeft className="h-3.5 w-3.5" />
                                                    </button>
                                                    <button
                                                        type="button"
                                                        onClick={handleNextShowcase}
                                                        aria-label="Next showcase visual"
                                                        className="flex h-6 w-6 items-center justify-center rounded-md text-muted-foreground transition-colors hover:bg-muted hover:text-foreground cursor-pointer"
                                                    >
                                                        <ChevronRight className="h-3.5 w-3.5" />
                                                    </button>
                                                </div>

                                                <div className="flex items-center gap-1" role="tablist" aria-label="Showcase slides">
                                                    {showcaseCreatives.map((creative, index) => (
                                                        <button
                                                            key={creative.id}
                                                            type="button"
                                                            onClick={() => setActiveShowcaseIndex(index)}
                                                            role="tab"
                                                            aria-selected={activeShowcaseIndex === index}
                                                            aria-label={`Show ${creative.productName}`}
                                                            className={`h-1.5 rounded-full transition-all duration-300 cursor-pointer ${
                                                                activeShowcaseIndex === index
                                                                    ? 'w-4 bg-primary'
                                                                    : 'w-1.5 bg-muted-foreground/30 hover:bg-muted-foreground/60'
                                                            }`}
                                                        />
                                                    ))}
                                                </div>

                                                <span className="font-mono text-[10px] text-muted-foreground">
                                                    0{activeShowcaseIndex + 1} / 0{showcaseCreatives.length}
                                                </span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            {/* ==========================================================
                                INTERCONNECTED SYSTEM ARCHITECTURE FLOW
                            =========================================================== */}
                            <div
                                id="how-it-works"
                                className="border-t border-border/60 pt-8"
                            >
                                <div className="mx-auto mb-8 max-w-2xl space-y-2 text-center">
                                    <div className="inline-flex items-center gap-1.5 rounded-full border border-primary/20 bg-primary/10 px-3 py-0.5 text-xs font-bold text-primary">
                                        <Layers className="h-3.5 w-3.5" />
                                        End-to-End System Engine
                                    </div>
                                    <h2 className="text-xl font-extrabold tracking-tight text-foreground sm:text-2xl">
                                        How All System Capabilities Connect
                                    </h2>
                                    <p className="text-xs text-muted-foreground sm:text-sm">
                                        From raw catalog inventory to calendar-synchronized campaign launches.
                                    </p>
                                </div>

                                <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">
                                    {[
                                        {
                                            step: '01',
                                            title: 'Product Catalog',
                                            desc: 'Manage your retail products, custom descriptions, pricing, and product imagery.',
                                            icon: Package,
                                            color: 'text-purple-500',
                                            bg: 'bg-purple-500/10',
                                            route: '/products',
                                        },
                                        {
                                            step: '02',
                                            title: 'Philippine Calendar',
                                            desc: 'Official Proclamation regular holidays, special dates, and 15/30 payday retail cycles.',
                                            icon: CalendarDays,
                                            color: 'text-amber-500',
                                            bg: 'bg-amber-500/10',
                                            route: '/calendar',
                                        },
                                        {
                                            step: '03',
                                            title: 'Creative Studio',
                                            desc: 'Synthesize tailored promotional creatives with customizable vibes, styles, and dimensions.',
                                            icon: ImageIcon,
                                            color: 'text-primary',
                                            bg: 'bg-primary/10',
                                            route: '/generator',
                                        },
                                        {
                                            step: '04',
                                            title: 'Campaign Pipeline',
                                            desc: 'Organize generated visuals into scheduled marketing campaigns and multi-channel exports.',
                                            icon: Megaphone,
                                            color: 'text-emerald-500',
                                            bg: 'bg-emerald-500/10',
                                            route: '/campaigns',
                                        },
                                    ].map((item) => {
                                        const Icon = item.icon;

                                        return (
                                            <div
                                                key={item.step}
                                                className="group relative flex flex-col justify-between rounded-3xl border border-white/25 bg-card/85 p-5 shadow-lg backdrop-blur-2xl transition-all duration-200 hover:-translate-y-1 hover:border-primary/40 hover:shadow-2xl dark:border-white/10 dark:bg-card/85"
                                            >
                                                <div>
                                                    <div className="mb-3 flex items-center justify-between">
                                                        <span className="rounded-md bg-muted/60 px-2 py-0.5 font-mono text-[11px] font-extrabold text-muted-foreground">
                                                            {item.step}
                                                        </span>
                                                        <div
                                                            className={`flex h-8 w-8 items-center justify-center rounded-xl ${item.bg} ${item.color} shadow-xs`}
                                                        >
                                                            <Icon className="h-4 w-4" />
                                                        </div>
                                                    </div>

                                                    <h3 className="text-sm font-bold text-foreground transition-colors group-hover:text-primary">
                                                        {item.title}
                                                    </h3>
                                                    <p className="mt-1 text-xs leading-relaxed text-muted-foreground">
                                                        {item.desc}
                                                    </p>
                                                </div>

                                                <div className="mt-3 flex items-center justify-between border-t border-border/50 pt-3 text-[11px]">
                                                    <span className="font-semibold text-primary">
                                                        Connected Feature
                                                    </span>
                                                    <span className="text-muted-foreground transition-transform group-hover:translate-x-1">
                                                        &rarr;
                                                    </span>
                                                </div>
                                            </div>
                                        );
                                    })}
                                </div>
                            </div>
                        </div>
                    </section>

                    {/* ==========================================================
                        CORE VALUE PILLARS / CAPABILITIES
                    =========================================================== */}

                    <section
                        id="features"
                        className="border-b border-border/70 bg-background py-16 md:py-24"
                    >
                        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
                            <div className="mx-auto max-w-3xl space-y-3 text-center">
                                <Badge
                                    variant="outline"
                                    className="border-primary/20 bg-primary/10 text-xs font-bold text-primary"
                                >
                                    System Architecture
                                </Badge>
                                <h2 className="text-2xl font-bold tracking-tight text-foreground sm:text-3xl md:text-4xl">
                                    Engineered for Philippine retail & digital
                                    commerce.
                                </h2>
                                <p className="text-sm text-muted-foreground md:text-base">
                                    Eliminate creative bottlenecks. MarketPilot
                                    ties your inventory and promotions directly
                                    into national holiday cycles.
                                </p>
                            </div>

                            <div className="mt-12 grid gap-6 sm:grid-cols-2 lg:grid-cols-4">
                                {/* Pillar 1 */}
                                <div className="space-y-3 rounded-2xl border border-border bg-card p-6 shadow-xs">
                                    <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-blue-500/10 text-blue-500">
                                        <ImageIcon className="h-5 w-5" />
                                    </div>
                                    <h3 className="text-base font-bold text-foreground">
                                        Commercial Visual Studio
                                    </h3>
                                    <p className="text-xs leading-relaxed text-muted-foreground">
                                        Generate commercial-grade product photography, seasonal promotional banners, and ad mockups tailored to your exact brand tone.
                                    </p>
                                </div>

                                {/* Pillar 2 */}
                                <div className="space-y-3 rounded-2xl border border-border bg-card p-6 shadow-xs">
                                    <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-amber-500/10 text-amber-500">
                                        <CalendarDays className="h-5 w-5" />
                                    </div>
                                    <h3 className="text-base font-bold text-foreground">
                                        Philippine Holiday Engine
                                    </h3>
                                    <p className="text-xs leading-relaxed text-muted-foreground">
                                        Track official regular holidays, special non-working days, Islamic movable dates, and long-weekend opportunities with automatic 60-day forecasts.
                                    </p>
                                </div>

                                {/* Pillar 3 */}
                                <div className="space-y-3 rounded-2xl border border-border bg-card p-6 shadow-xs">
                                    <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-emerald-500/10 text-emerald-500">
                                        <Package className="h-5 w-5" />
                                    </div>
                                    <h3 className="text-base font-bold text-foreground">
                                        Product Catalog Sync
                                    </h3>
                                    <p className="text-xs leading-relaxed text-muted-foreground">
                                        Organize offerings with pricing, category tags, and reference photos. Select any item to instantly populate campaign creatives.
                                    </p>
                                </div>

                                {/* Pillar 4 */}
                                <div className="space-y-3 rounded-2xl border border-border bg-card p-6 shadow-xs">
                                    <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-purple-500/10 text-purple-500">
                                        <Layers className="h-5 w-5" />
                                    </div>
                                    <h3 className="text-base font-bold text-foreground">
                                        Multi-Channel Campaigns
                                    </h3>
                                    <p className="text-xs leading-relaxed text-muted-foreground">
                                        Group visual assets into scheduled campaigns, track active marketing pipelines, and export in PNG, JPEG, or SVG format anytime.
                                    </p>
                                </div>
                            </div>
                        </div>
                    </section>

                    {/* ==========================================================
                        INTERACTIVE PHILIPPINE MARKETING CALENDAR SHOWCASE
                    =========================================================== */}

                    <section
                        id="calendar-engine"
                        className="border-b border-border/70 bg-card/40 py-16 md:py-24"
                    >
                        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
                            <div className="grid gap-10 lg:grid-cols-12 lg:items-center">
                                {/* Left Side: Explanation */}
                                <div className="space-y-4 lg:col-span-5">
                                    <Badge
                                        variant="outline"
                                        className="border-amber-500/20 bg-amber-500/10 text-xs font-bold text-amber-500"
                                    >
                                        Official National Data
                                    </Badge>
                                    <h2 className="text-2xl font-bold tracking-tight text-foreground sm:text-3xl">
                                        Never miss a holiday revenue window.
                                    </h2>
                                    <p className="text-sm leading-relaxed text-muted-foreground">
                                        Filipino consumers shop actively around long weekends, national holidays, and payday intervals. MarketPilot gives you a proactive 60-day visual launch radar.
                                    </p>

                                    <div className="space-y-2 pt-2">
                                        <div className="flex items-center gap-2.5 text-xs font-semibold text-foreground">
                                            <span className="h-2 w-2 rounded-full bg-blue-500" />
                                            <span>
                                                Regular National Holidays (Full Proclamation Sync)
                                            </span>
                                        </div>
                                        <div className="flex items-center gap-2.5 text-xs font-semibold text-foreground">
                                            <span className="h-2 w-2 rounded-full bg-amber-500" />
                                            <span>
                                                Special Non-Working Days & Shifted Dates
                                            </span>
                                        </div>
                                        <div className="flex items-center gap-2.5 text-xs font-semibold text-foreground">
                                            <span className="h-2 w-2 rounded-full bg-emerald-500" />
                                            <span>
                                                Islamic Movable Holidays & National Proclamations
                                            </span>
                                        </div>
                                        <div className="flex items-center gap-2.5 text-xs font-semibold text-foreground">
                                            <span className="h-2 w-2 rounded-full bg-purple-500" />
                                            <span>
                                                Mid-Month & End-Month Payday Sale Cycles
                                            </span>
                                        </div>
                                    </div>

                                    <div className="pt-2">
                                        <Button
                                            asChild
                                            size="sm"
                                            className="h-10 rounded-xl px-4 text-xs font-bold shadow-md shadow-primary/20"
                                        >
                                            <Link href={register()}>
                                                Sync Your Store Calendar &rarr;
                                            </Link>
                                        </Button>
                                    </div>
                                </div>

                                {/* Right Side: Interactive Calendar Showcase */}
                                <div className="lg:col-span-7">
                                    <div className="overflow-hidden rounded-3xl border border-white/25 bg-card/85 p-6 shadow-2xl backdrop-blur-2xl dark:border-white/10 dark:bg-card/85">
                                        <div className="mb-5 flex flex-wrap items-center justify-between gap-3 border-b border-border/80 pb-4">
                                            <div className="flex items-center gap-2">
                                                <Calendar className="h-5 w-5 text-amber-500" />
                                                <h3 className="text-sm font-bold text-foreground">
                                                    Philippine National Holiday Forecast
                                                </h3>
                                            </div>

                                            {/* Filter Tabs */}
                                            <div className="flex items-center gap-1 text-[11px] font-semibold">
                                                {(
                                                    [
                                                        'all',
                                                        'regular',
                                                        'special_non_working',
                                                    ] as const
                                                ).map((cat) => (
                                                    <button
                                                        key={cat}
                                                        type="button"
                                                        onClick={() =>
                                                            setCalendarCategory(
                                                                cat,
                                                            )
                                                        }
                                                        className={`cursor-pointer rounded-lg px-2.5 py-1 transition-all ${calendarCategory === cat ? 'bg-primary text-primary-foreground shadow-2xs' : 'text-muted-foreground hover:text-foreground'}`}
                                                    >
                                                        {cat === 'all'
                                                            ? 'All Dates'
                                                            : cat === 'regular'
                                                              ? 'Regular'
                                                              : 'Special'}
                                                    </button>
                                                ))}
                                            </div>
                                        </div>

                                        <div className="grid gap-3 sm:grid-cols-2">
                                            {filteredDates.map((evt) => (
                                                <div
                                                    key={evt.name}
                                                    className="group flex flex-col justify-between rounded-2xl border border-border/70 bg-card/60 p-3.5 shadow-2xs transition-all duration-200 hover:-translate-y-0.5 hover:border-amber-500/40 hover:shadow-md"
                                                >
                                                    <div className="mb-2">
                                                        <div className="flex items-center justify-between">
                                                            <span className="font-mono text-xs font-bold text-primary">
                                                                {evt.date}
                                                            </span>
                                                            <Badge
                                                                variant="outline"
                                                                className={`text-[9px] font-bold ${evt.type === 'Regular Holiday' ? 'border-blue-500/30 bg-blue-500/10 text-blue-500' : 'border-amber-500/30 bg-amber-500/10 text-amber-500'}`}
                                                            >
                                                                {evt.type}
                                                            </Badge>
                                                        </div>
                                                        <p className="mt-1 font-bold text-foreground">
                                                            {evt.name}
                                                        </p>
                                                    </div>

                                                    <div className="flex items-center justify-between border-t border-border/40 pt-1.5 text-[11px]">
                                                        <span className="text-muted-foreground">
                                                            {evt.days}
                                                        </span>
                                                        {evt.longWeekend && (
                                                            <span className="font-semibold text-emerald-500">
                                                                Long Weekend
                                                            </span>
                                                        )}
                                                    </div>
                                                </div>
                                            ))}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </section>

                    {/* ==========================================================
                        SUBSCRIPTION PLANS
                    =========================================================== */}

                    <section
                        id="subscriptions"
                        className="border-b border-border/70 bg-background py-16 md:py-24"
                    >
                        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
                            <div className="mx-auto max-w-2xl space-y-3 text-center">
                                <Badge
                                    variant="outline"
                                    className="border-primary/20 bg-primary/10 text-xs font-bold text-primary"
                                >
                                    Subscription Plans
                                </Badge>
                                <h2 className="text-2xl font-bold tracking-tight text-foreground sm:text-3xl md:text-4xl">
                                    Flexible subscription tiers for growing retail brands.
                                </h2>
                                <p className="text-sm text-muted-foreground">
                                    Choose the right plan to power your seasonal marketing campaigns and visual creative workflows.
                                </p>

                                {/* Billing cycle selector */}
                                <div className="flex items-center justify-center gap-3 pt-2">
                                    <button
                                        type="button"
                                        onClick={() =>
                                            setBillingCycle('monthly')
                                        }
                                        className={`cursor-pointer rounded-lg px-3.5 py-1.5 text-xs font-bold transition-all ${billingCycle === 'monthly' ? 'bg-primary text-primary-foreground shadow-xs' : 'text-muted-foreground hover:text-foreground'}`}
                                    >
                                        Monthly Subscription
                                    </button>
                                    <button
                                        type="button"
                                        onClick={() =>
                                            setBillingCycle('annual')
                                        }
                                        className={`flex cursor-pointer items-center gap-1.5 rounded-lg px-3.5 py-1.5 text-xs font-bold transition-all ${billingCycle === 'annual' ? 'bg-primary text-primary-foreground shadow-xs' : 'text-muted-foreground hover:text-foreground'}`}
                                    >
                                        <span>Annual Subscription</span>
                                        <Badge className="bg-emerald-500 px-1.5 py-0 text-[10px] font-extrabold text-white">
                                            Save 20%
                                        </Badge>
                                    </button>
                                </div>
                            </div>

                            <div className="mx-auto mt-12 grid max-w-5xl gap-6 lg:grid-cols-3">
                                {/* Starter Subscription */}
                                <div className="group flex flex-col justify-between space-y-6 rounded-3xl border border-border/80 bg-card/85 p-6 shadow-md backdrop-blur-xl transition-all duration-200 hover:-translate-y-1 hover:border-primary/40 hover:shadow-xl dark:border-white/10 dark:bg-card/85">
                                    <div className="space-y-4">
                                        <div className="space-y-1">
                                            <div className="flex items-center justify-between">
                                                <h3 className="text-base font-bold text-foreground">
                                                    Starter Plan
                                                </h3>
                                                <Badge variant="outline" className="text-[10px] font-bold text-muted-foreground">
                                                    Free Access
                                                </Badge>
                                            </div>
                                            <p className="text-xs text-muted-foreground">
                                                Ideal for exploring the studio and tracking key holiday dates.
                                            </p>
                                        </div>
                                        <div className="rounded-xl border border-border/60 bg-muted/20 p-3 text-center">
                                            <p className="text-xs font-bold text-foreground">Community Starter</p>
                                            <p className="text-[11px] text-muted-foreground">Free forever / No credit card</p>
                                        </div>
                                        <ul className="space-y-2.5 pt-2 text-xs text-muted-foreground">
                                            <li className="flex items-center gap-2">
                                                <Check className="h-4 w-4 shrink-0 text-emerald-500" />
                                                <span>
                                                    15 Visual creations per month
                                                </span>
                                            </li>
                                            <li className="flex items-center gap-2">
                                                <Check className="h-4 w-4 shrink-0 text-emerald-500" />
                                                <span>
                                                    Official Philippine Holiday Calendar
                                                </span>
                                            </li>
                                            <li className="flex items-center gap-2">
                                                <Check className="h-4 w-4 shrink-0 text-emerald-500" />
                                                <span>
                                                    Up to 10 catalog products
                                                </span>
                                            </li>
                                            <li className="flex items-center gap-2">
                                                <Check className="h-4 w-4 shrink-0 text-emerald-500" />
                                                <span>
                                                    High-res PNG download
                                                </span>
                                            </li>
                                        </ul>
                                    </div>

                                    <Button
                                        asChild
                                        variant="outline"
                                        className="h-10 w-full rounded-xl text-xs font-bold shadow-none transition-all hover:bg-muted/60"
                                    >
                                        <Link href={register()}>
                                            Get Started Free
                                        </Link>
                                    </Button>
                                </div>

                                {/* Pro Growth Subscription (Highlighted) */}
                                <div className="group relative flex flex-col justify-between space-y-6 rounded-3xl border-2 border-primary bg-card/95 p-6 shadow-xl backdrop-blur-2xl transition-all duration-200 hover:-translate-y-1 hover:shadow-2xl hover:shadow-primary/15">
                                    <div className="absolute -top-3 left-1/2 -translate-x-1/2 rounded-md bg-primary px-3 py-0.5 text-[10px] font-extrabold tracking-wider text-primary-foreground uppercase shadow-sm">
                                        Recommended
                                    </div>
                                    <div className="space-y-4">
                                        <div className="space-y-1">
                                            <div className="flex items-center justify-between">
                                                <h3 className="text-base font-bold text-foreground">
                                                    Growth Professional
                                                </h3>
                                                <Badge className="bg-primary/10 text-[10px] font-bold text-primary">
                                                    Full Access
                                                </Badge>
                                            </div>
                                            <p className="text-xs text-muted-foreground">
                                                For active online sellers & retail MSMEs.
                                            </p>
                                        </div>
                                        <div className="rounded-xl border border-primary/20 bg-primary/5 p-3 text-center">
                                            <p className="text-xs font-bold text-primary">Professional Subscription</p>
                                            <p className="text-[11px] text-muted-foreground">Unlimited generation capacity</p>
                                        </div>
                                        <ul className="space-y-2.5 pt-2 text-xs text-muted-foreground">
                                            <li className="flex items-center gap-2">
                                                <Check className="h-4 w-4 shrink-0 text-emerald-500" />
                                                <span className="font-semibold text-foreground">
                                                    Unlimited Visual Generations
                                                </span>
                                            </li>
                                            <li className="flex items-center gap-2">
                                                <Check className="h-4 w-4 shrink-0 text-emerald-500" />
                                                <span>
                                                    Full Philippine Calendar + Custom Events
                                                </span>
                                            </li>
                                            <li className="flex items-center gap-2">
                                                <Check className="h-4 w-4 shrink-0 text-emerald-500" />
                                                <span>
                                                    Unlimited Catalog Products
                                                </span>
                                            </li>
                                            <li className="flex items-center gap-2">
                                                <Check className="h-4 w-4 shrink-0 text-emerald-500" />
                                                <span>
                                                    PNG, JPEG & SVG Vector Exports
                                                </span>
                                            </li>
                                            <li className="flex items-center gap-2">
                                                <Check className="h-4 w-4 shrink-0 text-emerald-500" />
                                                <span>
                                                    Business Identity & Brand Tone Presets
                                                </span>
                                            </li>
                                        </ul>
                                    </div>

                                    <Button
                                        asChild
                                        className="h-10 w-full rounded-xl text-xs font-bold shadow-md shadow-primary/25 transition-all duration-200 hover:scale-[1.02] hover:shadow-lg hover:shadow-primary/30"
                                    >
                                        <Link href={register()}>
                                            Start 14-Day Free Trial
                                        </Link>
                                    </Button>
                                </div>

                                {/* Enterprise Subscription */}
                                <div className="group flex flex-col justify-between space-y-6 rounded-3xl border border-border/80 bg-card/85 p-6 shadow-md backdrop-blur-xl transition-all duration-200 hover:-translate-y-1 hover:border-primary/40 hover:shadow-xl dark:border-white/10 dark:bg-card/85">
                                    <div className="space-y-4">
                                        <div className="space-y-1">
                                            <div className="flex items-center justify-between">
                                                <h3 className="text-base font-bold text-foreground">
                                                    Scale & Agency
                                                </h3>
                                                <Badge variant="outline" className="text-[10px] font-bold text-muted-foreground">
                                                    Multi-Brand
                                                </Badge>
                                            </div>
                                            <p className="text-xs text-muted-foreground">
                                                For multi-brand retailers & marketing agencies.
                                            </p>
                                        </div>
                                        <div className="rounded-xl border border-border/60 bg-muted/20 p-3 text-center">
                                            <p className="text-xs font-bold text-foreground">Agency Subscription</p>
                                            <p className="text-[11px] text-muted-foreground">Dedicated workspace & support</p>
                                        </div>
                                        <ul className="space-y-2.5 pt-2 text-xs text-muted-foreground">
                                            <li className="flex items-center gap-2">
                                                <Check className="h-4 w-4 shrink-0 text-emerald-500" />
                                                <span className="font-semibold text-foreground">
                                                    Multi-Brand Workspace Management
                                                </span>
                                            </li>
                                            <li className="flex items-center gap-2">
                                                <Check className="h-4 w-4 shrink-0 text-emerald-500" />
                                                <span>
                                                    Bulk Asset Export & Campaign Packaging
                                                </span>
                                            </li>
                                            <li className="flex items-center gap-2">
                                                <Check className="h-4 w-4 shrink-0 text-emerald-500" />
                                                <span>
                                                    Priority Rendering Pipeline
                                                </span>
                                            </li>
                                            <li className="flex items-center gap-2">
                                                <Check className="h-4 w-4 shrink-0 text-emerald-500" />
                                                <span>
                                                    Dedicated Account Manager & Training
                                                </span>
                                            </li>
                                        </ul>
                                    </div>

                                    <Button
                                        asChild
                                        variant="outline"
                                        className="h-10 w-full rounded-xl text-xs font-bold shadow-none transition-all hover:bg-muted/60"
                                    >
                                        <Link href={register()}>
                                            Contact Sales
                                        </Link>
                                    </Button>
                                </div>
                            </div>
                        </div>
                    </section>

                    {/* ==========================================================
                        FREQUENTLY ASKED QUESTIONS
                    =========================================================== */}

                    <section
                        id="faq"
                        className="border-b border-border/70 bg-card/40 py-16 md:py-24"
                    >
                        <div className="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8">
                            <div className="mb-10 space-y-3 text-center">
                                <Badge
                                    variant="outline"
                                    className="border-primary/20 bg-primary/10 text-xs font-bold text-primary"
                                >
                                    Knowledge Base
                                </Badge>
                                <h2 className="text-2xl font-bold tracking-tight text-foreground sm:text-3xl">
                                    Frequently Asked Questions
                                </h2>
                            </div>

                            <div className="space-y-3">
                                {faqs.map((faq, idx) => (
                                    <div
                                        key={faq.q}
                                        className="overflow-hidden rounded-2xl border border-border bg-card transition-all"
                                    >
                                        <button
                                            type="button"
                                            onClick={() =>
                                                setOpenFaqIndex(
                                                    openFaqIndex === idx
                                                        ? null
                                                        : idx,
                                                )
                                            }
                                            className="flex w-full items-center justify-between p-4 text-left text-xs font-bold text-foreground transition-colors hover:text-primary sm:p-5 sm:text-sm"
                                        >
                                            <span>{faq.q}</span>
                                            <ChevronDown
                                                className={`h-4 w-4 shrink-0 transition-transform duration-200 ${openFaqIndex === idx ? 'rotate-180 text-primary' : 'text-muted-foreground'}`}
                                            />
                                        </button>

                                        {openFaqIndex === idx && (
                                            <div className="animate-in border-t border-border/50 px-4 pt-1 pb-5 text-xs leading-relaxed text-muted-foreground duration-150 fade-in sm:px-5">
                                                {faq.a}
                                            </div>
                                        )}
                                    </div>
                                ))}
                            </div>
                        </div>
                    </section>

                    {/* ==========================================================
                        CALL TO ACTION BANNER
                    =========================================================== */}

                    <section className="bg-background py-16 md:py-20">
                        <div className="mx-auto max-w-5xl px-4 sm:px-6 lg:px-8">
                            <div className="space-y-5 rounded-3xl border border-primary/30 bg-primary/5 p-8 text-center md:p-12">
                                <Badge
                                    variant="outline"
                                    className="border-primary/20 bg-primary/10 text-xs font-bold text-primary"
                                >
                                    Ready to automate your marketing?
                                </Badge>
                                <h2 className="mx-auto max-w-2xl text-2xl font-extrabold tracking-tight text-foreground sm:text-3xl md:text-4xl">
                                    Start generating seasonal marketing
                                    creatives in seconds.
                                </h2>
                                <p className="mx-auto max-w-lg text-xs text-muted-foreground sm:text-sm">
                                    Join retail businesses across the
                                    Philippines who use MarketPilot to turn
                                    national holidays and product launches into
                                    revenue.
                                </p>
                                <div className="flex flex-wrap items-center justify-center gap-3 pt-2">
                                    <Button
                                        asChild
                                        size="lg"
                                        className="h-11 gap-2 rounded-xl px-6 text-xs font-bold shadow-sm"
                                    >
                                        <Link href={register()}>
                                            <span>Get Started for Free</span>
                                            <ArrowRight className="h-4 w-4" />
                                        </Link>
                                    </Button>
                                    <Button
                                        asChild
                                        variant="outline"
                                        size="lg"
                                        className="h-11 rounded-xl px-5 text-xs font-semibold shadow-none"
                                    >
                                        <Link href={login()}>
                                            Sign In to Workspace
                                        </Link>
                                    </Button>
                                </div>
                            </div>
                        </div>
                    </section>
                </main>

                {/* ==========================================================
                    COMPREHENSIVE PROFESSIONAL FOOTER
                =========================================================== */}

                <footer className="border-t border-border bg-card/80 text-xs text-muted-foreground">
                    <div className="mx-auto max-w-7xl px-4 py-12 sm:px-6 md:py-16 lg:px-8">
                        <div className="grid grid-cols-2 gap-8 md:grid-cols-5">
                            {/* Brand Summary Column */}
                            <div className="col-span-2 space-y-4">
                                <div className="flex items-center gap-2.5">
                                    <div className="flex h-8 w-8 items-center justify-center rounded-xl bg-primary text-primary-foreground shadow-xs">
                                        <AppLogoIcon className="h-4 w-4 fill-current" />
                                    </div>
                                    <span className="text-sm font-bold tracking-tight text-foreground">
                                        MarketPilot
                                    </span>
                                </div>
                                <p className="max-w-xs text-xs leading-relaxed text-muted-foreground">
                                    AI-powered retail marketing automation &
                                    creative visual generator aligned with
                                    official Philippine national holidays and
                                    commercial retail cycles.
                                </p>
                                <div className="flex items-center gap-2 text-[11px] font-semibold text-emerald-500">
                                    <span className="h-2 w-2 animate-pulse rounded-full bg-emerald-500" />
                                    <span>
                                        Philippine Holiday API Active & Synced
                                    </span>
                                </div>
                            </div>

                            {/* Column 1: Core Platform */}
                            <div className="space-y-3">
                                <p className="text-[11px] font-bold tracking-wider text-foreground uppercase">
                                    Platform
                                </p>
                                <ul className="space-y-2">
                                    <li>
                                        <a
                                            href="#hero-studio"
                                            className="transition-colors hover:text-primary"
                                        >
                                            AI Creative Studio
                                        </a>
                                    </li>
                                    <li>
                                        <a
                                            href="#calendar-engine"
                                            className="transition-colors hover:text-primary"
                                        >
                                            Philippine Marketing Calendar
                                        </a>
                                    </li>
                                    <li>
                                        <Link
                                            href={login()}
                                            className="transition-colors hover:text-primary"
                                        >
                                            Product Offerings Catalog
                                        </Link>
                                    </li>
                                    <li>
                                        <Link
                                            href={login()}
                                            className="transition-colors hover:text-primary"
                                        >
                                            Campaign Management Hub
                                        </Link>
                                    </li>
                                    <li>
                                        <a
                                            href="#hero-studio"
                                            className="transition-colors hover:text-primary"
                                        >
                                            PNG, JPEG & SVG Exports
                                        </a>
                                    </li>
                                </ul>
                            </div>

                            {/* Column 2: Holiday Intelligence */}
                            <div className="space-y-3">
                                <p className="text-[11px] font-bold tracking-wider text-foreground uppercase">
                                    PH Holidays
                                </p>
                                <ul className="space-y-2">
                                    <li>
                                        <a
                                            href="#calendar-engine"
                                            className="transition-colors hover:text-primary"
                                        >
                                            Regular National Holidays
                                        </a>
                                    </li>
                                    <li>
                                        <a
                                            href="#calendar-engine"
                                            className="transition-colors hover:text-primary"
                                        >
                                            Special Non-Working Days
                                        </a>
                                    </li>
                                    <li>
                                        <a
                                            href="#calendar-engine"
                                            className="transition-colors hover:text-primary"
                                        >
                                            Islamic Movable Dates
                                        </a>
                                    </li>
                                    <li>
                                        <a
                                            href="#calendar-engine"
                                            className="transition-colors hover:text-primary"
                                        >
                                            Long Weekend Metadata
                                        </a>
                                    </li>
                                    <li>
                                        <a
                                            href="#calendar-engine"
                                            className="transition-colors hover:text-primary"
                                        >
                                            Proclamation Sync Engine
                                        </a>
                                    </li>
                                </ul>
                            </div>

                            {/* Column 3: Company & Legal */}
                            <div className="space-y-3">
                                <p className="text-[11px] font-bold tracking-wider text-foreground uppercase">
                                    Account & Legal
                                </p>
                                <ul className="space-y-2">
                                    <li>
                                        <Link
                                            href={login()}
                                            className="transition-colors hover:text-primary"
                                        >
                                            Sign In
                                        </Link>
                                    </li>
                                    <li>
                                        <Link
                                            href={register()}
                                            className="transition-colors hover:text-primary"
                                        >
                                            Register Account
                                        </Link>
                                    </li>
                                    <li>
                                        <a
                                            href="#faq"
                                            className="transition-colors hover:text-primary"
                                        >
                                            FAQ & Support
                                        </a>
                                    </li>
                                    <li>
                                        <span className="text-muted-foreground/60">
                                            Privacy Policy
                                        </span>
                                    </li>
                                    <li>
                                        <span className="text-muted-foreground/60">
                                            Terms of Service
                                        </span>
                                    </li>
                                </ul>
                            </div>
                        </div>

                        {/* Bottom Copyright Bar */}
                        <div className="mt-12 flex flex-col items-center justify-between gap-3 border-t border-border pt-6 text-[11px] sm:flex-row">
                            <p>
                                © {new Date().getFullYear()} MarketPilot. All
                                rights reserved.
                            </p>
                            <p className="text-muted-foreground">
                                Built for Philippine Retailers, Online Sellers &
                                Modern MSMEs.
                            </p>
                        </div>
                    </div>
                </footer>
            </div>
        </>
    );
}
